// Turns tokens/tokens.json into Tailwind v4 `@theme` CSS variables.
// Run with: npm run tokens   (also runs automatically before dev, build and check)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const input = resolve(root, "tokens/tokens.json");
const output = resolve(root, "src/styles/tokens.generated.css");

const tokens = JSON.parse(readFileSync(input, "utf8"));
const lines = [];

const fail = (message) => {
  console.error(`tokens: ${message}`);
  process.exit(1);
};

for (const group of ["color", "radius", "font", "shadow", "text", "spacing"]) {
  if (!tokens[group]) fail(`missing "${group}" in tokens/tokens.json`);
}

// Reset Tailwind's default palette so only YOUR colors exist.
// (bg-blue-500 will not work; bg-primary will.)
lines.push("  --color-*: initial;");

for (const [name, value] of Object.entries(tokens.color)) {
  lines.push(`  --color-${name}: ${value};`);
}
for (const [name, value] of Object.entries(tokens.radius)) {
  lines.push(`  --radius-${name}: ${value};`);
}
for (const [name, value] of Object.entries(tokens.font)) {
  lines.push(`  --font-${name}: ${value};`);
}
for (const [name, value] of Object.entries(tokens.shadow)) {
  lines.push(`  --shadow-${name}: ${value};`);
}
for (const [name, { size, lineHeight }] of Object.entries(tokens.text)) {
  if (!size || !lineHeight) fail(`text.${name} needs "size" and "lineHeight"`);
  lines.push(`  --text-${name}: ${size};`);
  lines.push(`  --text-${name}--line-height: ${lineHeight};`);
}
if (!tokens.spacing.base) fail('spacing needs a "base" value');
lines.push(`  --spacing: ${tokens.spacing.base};`);

const css = `/* AUTO-GENERATED by scripts/build-tokens.mjs from tokens/tokens.json.
   Do not edit by hand. Change tokens/tokens.json and run: npm run tokens */
@theme {
${lines.join("\n")}
}
`;

mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, css);
console.log(`tokens: wrote ${lines.length} variables to src/styles/tokens.generated.css`);
